CATEGORY_CHOICES = (
    ("CR", "Crud"),
    ("ML", "Milk"),
    ("LS", "Lassi"),
    ("MS", "Milkshake"),
    ("GH", "Ghee"),
    ("PN", "Paneer"),
)

STATE_CHOICES = (
    ('AF', 'Afghanistan'),
    ('AL', 'Albania'),
    ('DZ', 'Algeria'),
    ('AR', 'Argentina'),
    ('AU', 'Australia'),
    ('AT', 'Austria'),
    ('BD', 'Bangladesh'),
    ('BE', 'Belgium'),
    ('BR', 'Brazil'),
    ('CA', 'Canada'),
    ('CL', 'Chile'),
    ('CN', 'China'),
    ('CO', 'Colombia'),
    ('CZ', 'Czech Republic'),
    ('DK', 'Denmark'),
    ('EG', 'Egypt'),
    ('FI', 'Finland'),
    ('FR', 'France'),
    ('DE', 'Germany'),
    ('GR', 'Greece'),
    ('HK', 'Hong Kong'),
    ('HU', 'Hungary'),
    ('IN', 'India'),
    ('ID', 'Indonesia'),
    ('IR', 'Iran'),
    ('IQ', 'Iraq'),
    ('IE', 'Ireland'),
    ('IL', 'Israel'),
    ('IT', 'Italy'),
    ('JP', 'Japan'),
    ('JO', 'Jordan'),
    ('KZ', 'Kazakhstan'),
    ('KR', 'South Korea'),
    ('KW', 'Kuwait'),
    ('LB', 'Lebanon'),
    ('MY', 'Malaysia'),
    ('MX', 'Mexico'),
    ('MA', 'Morocco'),
    ('NP', 'Nepal'),
    ('NL', 'Netherlands'),
    ('NZ', 'New Zealand'),
    ('NG', 'Nigeria'),
    ('NO', 'Norway'),
    ('PK', 'Pakistan'),
    ('PH', 'Philippines'),
    ('PL', 'Poland'),
    ('PT', 'Portugal'),
    ('QA', 'Qatar'),
    ('RO', 'Romania'),
    ('RU', 'Russia'),
    ('SA', 'Saudi Arabia'),
    ('SG', 'Singapore'),
    ('ZA', 'South Africa'),
    ('ES', 'Spain'),
    ('LK', 'Sri Lanka'),
    ('SE', 'Sweden'),
    ('CH', 'Switzerland'),
    ('SY', 'Syria'),
    ('TW', 'Taiwan'),
    ('TH', 'Thailand'),
    ('TR', 'Turkey'),
    ('UA', 'Ukraine'),
    ('AE', 'United Arab Emirates'),
    ('GB', 'United Kingdom'),
    ('US', 'United States'),
    ('VN', 'Vietnam'),
    ('YE', 'Yemen'),
)
