# Generated by Django 5.2 on 2025-04-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
