# Generated by Django 5.2 on 2025-04-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cartitem_delete_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='delete_at',
        ),
    ]
